\begin{Verbatim}[commandchars=\\\{\}]
\PY{n}{GD}\PY{p}{.}\PY{n}{BlendFunc}\PY{p}{(}\PY{n}{ONE}\PY{p}{,} \PY{n}{ONE\PYZus{}MINUS\PYZus{}SRC\PYZus{}ALPHA}\PY{p}{)}\PY{p}{;} 
\PY{n}{GD}\PY{p}{.}\PY{n}{cmd\PYZus{}clock}\PY{p}{(}\PY{l+m+mi}{136}\PY{p}{,} \PY{l+m+mi}{136}\PY{p}{,} \PY{l+m+mi}{130}\PY{p}{,}
             \PY{n}{OPT\PYZus{}NOTICKS} \PY{o}{|} \PY{n}{OPT\PYZus{}NOBACK}\PY{p}{,} \PY{l+m+mi}{8}\PY{p}{,} \PY{l+m+mi}{41}\PY{p}{,} \PY{l+m+mi}{39}\PY{p}{,} \PY{l+m+mi}{0}\PY{p}{)}\PY{p}{;} 
\end{Verbatim}
