\begin{Verbatim}[commandchars=\\\{\}]
\PY{n}{GD}\PY{p}{.}\PY{n}{Begin}\PY{p}{(}\PY{n}{BITMAPS}\PY{p}{)}\PY{p}{;}  
\PY{n}{GD}\PY{p}{.}\PY{n}{Vertex2ii}\PY{p}{(}  \PY{l+m+mi}{0}\PY{p}{,} \PY{l+m+mi}{10}\PY{p}{,} \PY{n}{WALK\PYZus{}HANDLE}\PY{p}{,} \PY{l+m+mi}{0}\PY{p}{)}\PY{p}{;}
\PY{n}{GD}\PY{p}{.}\PY{n}{Vertex2ii}\PY{p}{(} \PY{l+m+mi}{50}\PY{p}{,} \PY{l+m+mi}{10}\PY{p}{,} \PY{n}{WALK\PYZus{}HANDLE}\PY{p}{,} \PY{l+m+mi}{1}\PY{p}{)}\PY{p}{;}
\PY{n}{GD}\PY{p}{.}\PY{n}{Vertex2ii}\PY{p}{(}\PY{l+m+mi}{100}\PY{p}{,} \PY{l+m+mi}{10}\PY{p}{,} \PY{n}{WALK\PYZus{}HANDLE}\PY{p}{,} \PY{l+m+mi}{2}\PY{p}{)}\PY{p}{;}
\PY{n}{GD}\PY{p}{.}\PY{n}{Vertex2ii}\PY{p}{(}\PY{l+m+mi}{150}\PY{p}{,} \PY{l+m+mi}{10}\PY{p}{,} \PY{n}{WALK\PYZus{}HANDLE}\PY{p}{,} \PY{l+m+mi}{3}\PY{p}{)}\PY{p}{;}
\PY{n}{GD}\PY{p}{.}\PY{n}{Vertex2ii}\PY{p}{(}\PY{l+m+mi}{200}\PY{p}{,} \PY{l+m+mi}{10}\PY{p}{,} \PY{n}{WALK\PYZus{}HANDLE}\PY{p}{,} \PY{l+m+mi}{4}\PY{p}{)}\PY{p}{;}
\PY{n}{GD}\PY{p}{.}\PY{n}{Vertex2ii}\PY{p}{(}\PY{l+m+mi}{250}\PY{p}{,} \PY{l+m+mi}{10}\PY{p}{,} \PY{n}{WALK\PYZus{}HANDLE}\PY{p}{,} \PY{l+m+mi}{5}\PY{p}{)}\PY{p}{;}
\PY{n}{GD}\PY{p}{.}\PY{n}{Vertex2ii}\PY{p}{(}\PY{l+m+mi}{300}\PY{p}{,} \PY{l+m+mi}{10}\PY{p}{,} \PY{n}{WALK\PYZus{}HANDLE}\PY{p}{,} \PY{l+m+mi}{6}\PY{p}{)}\PY{p}{;}
\PY{n}{GD}\PY{p}{.}\PY{n}{Vertex2ii}\PY{p}{(}\PY{l+m+mi}{350}\PY{p}{,} \PY{l+m+mi}{10}\PY{p}{,} \PY{n}{WALK\PYZus{}HANDLE}\PY{p}{,} \PY{l+m+mi}{7}\PY{p}{)}\PY{p}{;} 
\end{Verbatim}
