\begin{Verbatim}[commandchars=\\\{\}]
\PY{n}{GD}\PY{p}{.}\PY{n}{Tag}\PY{p}{(}\PY{n}{TAG\PYZus{}DIAL}\PY{p}{)}\PY{p}{;} 
\PY{n}{GD}\PY{p}{.}\PY{n}{cmd\PYZus{}dial}\PY{p}{(}\PY{l+m+mi}{68}\PY{p}{,} \PY{l+m+mi}{68}\PY{p}{,} \PY{l+m+mi}{50}\PY{p}{,} \PY{n}{options}\PY{p}{,} \PY{n}{value}\PY{p}{)}\PY{p}{;}
\PY{n}{GD}\PY{p}{.}\PY{n}{cmd\PYZus{}track}\PY{p}{(}\PY{l+m+mi}{68}\PY{p}{,} \PY{l+m+mi}{68}\PY{p}{,} \PY{l+m+mi}{1}\PY{p}{,} \PY{l+m+mi}{1}\PY{p}{,} \PY{n}{TAG\PYZus{}DIAL}\PY{p}{)}\PY{p}{;}   
\end{Verbatim}
