\begin{Verbatim}[commandchars=\\\{\}]
\PY{n}{blobs}\PY{p}{[}\PY{n}{blob\PYZus{}i}\PY{p}{]}\PY{p}{.}\PY{n}{x} \PY{o}{=} \PY{n}{GD}\PY{p}{.}\PY{n}{inputs}\PY{p}{.}\PY{n}{x} \PY{o}{\PYZlt{}}\PY{o}{\PYZlt{}} \PY{l+m+mi}{4}\PY{p}{;} 
\PY{n}{blobs}\PY{p}{[}\PY{n}{blob\PYZus{}i}\PY{p}{]}\PY{p}{.}\PY{n}{y} \PY{o}{=} \PY{n}{GD}\PY{p}{.}\PY{n}{inputs}\PY{p}{.}\PY{n}{y} \PY{o}{\PYZlt{}}\PY{o}{\PYZlt{}} \PY{l+m+mi}{4}\PY{p}{;} 
\end{Verbatim}
