\begin{Verbatim}[commandchars=\\\{\}]
\PY{n}{GD}\PY{p}{.}\PY{n}{cmd\PYZus{}rotate}\PY{p}{(}\PY{n}{DEGREES}\PY{p}{(}\PY{l+m+mi}{73}\PY{p}{)}\PY{p}{)}\PY{p}{;}   
\PY{n}{GD}\PY{p}{.}\PY{n}{cmd\PYZus{}scale}\PY{p}{(}\PY{n}{F16}\PY{p}{(}\PY{l+m+mf}{0.3}\PY{p}{)}\PY{p}{,} \PY{n}{F16}\PY{p}{(}\PY{l+m+mi}{1}\PY{p}{)}\PY{p}{)}\PY{p}{;}
\PY{n}{GD}\PY{p}{.}\PY{n}{cmd\PYZus{}setmatrix}\PY{p}{(}\PY{p}{)}\PY{p}{;} 
\end{Verbatim}
