\begin{Verbatim}[commandchars=\\\{\}]
\PY{n}{GD}\PY{p}{.}\PY{n}{Clear}\PY{p}{(}\PY{p}{)}\PY{p}{;}   
\PY{n}{GD}\PY{p}{.}\PY{n}{ColorRGB}\PY{p}{(}\PY{l+m+mh}{0xf3d417}\PY{p}{)}\PY{p}{;}
\PY{n}{Poly} \PY{n}{po}\PY{p}{;}
\PY{n}{po}\PY{p}{.}\PY{n}{begin}\PY{p}{(}\PY{p}{)}\PY{p}{;}
\PY{n}{po}\PY{p}{.}\PY{n}{v}\PY{p}{(}\PY{l+m+mi}{16} \PY{o}{*} \PY{l+m+mi}{154}\PY{p}{,} \PY{l+m+mi}{16} \PY{o}{*} \PY{l+m+mi}{262}\PY{p}{)}\PY{p}{;}
\PY{n}{po}\PY{p}{.}\PY{n}{v}\PY{p}{(}\PY{l+m+mi}{16} \PY{o}{*} \PY{l+m+mi}{256}\PY{p}{,} \PY{l+m+mi}{16} \PY{o}{*} \PY{l+m+mi}{182}\PY{p}{)}\PY{p}{;}
\PY{n}{po}\PY{p}{.}\PY{n}{v}\PY{p}{(}\PY{l+m+mi}{16} \PY{o}{*} \PY{l+m+mi}{312}\PY{p}{,} \PY{l+m+mi}{16} \PY{o}{*} \PY{l+m+mi}{262}\PY{p}{)}\PY{p}{;}
\PY{n}{po}\PY{p}{.}\PY{n}{v}\PY{p}{(}\PY{l+m+mi}{16} \PY{o}{*} \PY{l+m+mi}{240}\PY{p}{,} \PY{l+m+mi}{16} \PY{o}{*}  \PY{l+m+mi}{10}\PY{p}{)}\PY{p}{;}
\PY{n}{po}\PY{p}{.}\PY{n}{draw}\PY{p}{(}\PY{p}{)}\PY{p}{;}
\PY{n}{GD}\PY{p}{.}\PY{n}{swap}\PY{p}{(}\PY{p}{)}\PY{p}{;}  
\end{Verbatim}
