\begin{Verbatim}[commandchars=\\\{\}]
\PY{n}{byte} \PY{n}{font} \PY{o}{=} \PY{n}{NIGHTFONT\PYZus{}HANDLE}\PY{p}{;}  
\PY{n}{GD}\PY{p}{.}\PY{n}{cmd\PYZus{}text}\PY{p}{(}\PY{l+m+mi}{240}\PY{p}{,} \PY{l+m+mi}{40}\PY{p}{,} \PY{n}{font}\PY{p}{,} \PY{n}{OPT\PYZus{}CENTER}\PY{p}{,} \PY{l+s}{\PYZdq{}}\PY{l+s}{abcdefghijklm}\PY{l+s}{\PYZdq{}}\PY{p}{)}\PY{p}{;}
\PY{n}{GD}\PY{p}{.}\PY{n}{cmd\PYZus{}text}\PY{p}{(}\PY{l+m+mi}{240}\PY{p}{,} \PY{l+m+mi}{100}\PY{p}{,} \PY{n}{font}\PY{p}{,} \PY{n}{OPT\PYZus{}CENTER}\PY{p}{,} \PY{l+s}{\PYZdq{}}\PY{l+s}{nopqrstuvwxyz}\PY{l+s}{\PYZdq{}}\PY{p}{)}\PY{p}{;}
\PY{n}{GD}\PY{p}{.}\PY{n}{cmd\PYZus{}text}\PY{p}{(}\PY{l+m+mi}{240}\PY{p}{,} \PY{l+m+mi}{160}\PY{p}{,} \PY{n}{font}\PY{p}{,} \PY{n}{OPT\PYZus{}CENTER}\PY{p}{,} \PY{l+s}{\PYZdq{}}\PY{l+s}{ABCDEFGHIJKLM}\PY{l+s}{\PYZdq{}}\PY{p}{)}\PY{p}{;}
\PY{n}{GD}\PY{p}{.}\PY{n}{cmd\PYZus{}text}\PY{p}{(}\PY{l+m+mi}{240}\PY{p}{,} \PY{l+m+mi}{220}\PY{p}{,} \PY{n}{font}\PY{p}{,} \PY{n}{OPT\PYZus{}CENTER}\PY{p}{,} \PY{l+s}{\PYZdq{}}\PY{l+s}{NOPQRSTUVWXYZ}\PY{l+s}{\PYZdq{}}\PY{p}{)}\PY{p}{;} 
\end{Verbatim}
