\begin{Verbatim}[commandchars=\\\{\}]
\PY{c+cp}{\PYZsh{}}\PY{c+cp}{define DARK\PYZus{}GREEN      0x007000  }
\PY{c+cp}{\PYZsh{}}\PY{c+cp}{define LIGHT\PYZus{}GREEN     0x33ff33}
\PY{c+cp}{\PYZsh{}}\PY{c+cp}{define DARK\PYZus{}RED        0x700000}
\PY{c+cp}{\PYZsh{}}\PY{c+cp}{define LIGHT\PYZus{}RED       0xff3333}
\PY{c+cp}{\PYZsh{}}\PY{c+cp}{define DARK\PYZus{}YELLOW     0x707000}
\PY{c+cp}{\PYZsh{}}\PY{c+cp}{define LIGHT\PYZus{}YELLOW    0xffff33}
\PY{c+cp}{\PYZsh{}}\PY{c+cp}{define DARK\PYZus{}BLUE       0x007070}
\PY{c+cp}{\PYZsh{}}\PY{c+cp}{define LIGHT\PYZus{}BLUE      0x33ffff  }
\end{Verbatim}
