\begin{Verbatim}[commandchars=\\\{\}]
  \PY{n}{GD}\PY{p}{.}\PY{n}{Tag}\PY{p}{(}\PY{n}{TAG\PYZus{}SLIDER}\PY{p}{)}\PY{p}{;} 
  \PY{n}{GD}\PY{p}{.}\PY{n}{cmd\PYZus{}slider}\PY{p}{(}\PY{l+m+mi}{16}\PY{p}{,} \PY{l+m+mi}{199}\PY{p}{,} \PY{l+m+mi}{104}\PY{p}{,} \PY{l+m+mi}{10}\PY{p}{,} \PY{n}{options}\PY{p}{,} \PY{n}{value}\PY{p}{,} \PY{l+m+mi}{65535}\PY{p}{)}\PY{p}{;}
  \PY{n}{GD}\PY{p}{.}\PY{n}{cmd\PYZus{}track}\PY{p}{(}\PY{l+m+mi}{16}\PY{p}{,} \PY{l+m+mi}{199}\PY{p}{,} \PY{l+m+mi}{104}\PY{p}{,} \PY{l+m+mi}{10}\PY{p}{,} \PY{n}{TAG\PYZus{}SLIDER}\PY{p}{)}\PY{p}{;}

  \PY{n}{GD}\PY{p}{.}\PY{n}{Tag}\PY{p}{(}\PY{n}{TAG\PYZus{}TOGGLE}\PY{p}{)}\PY{p}{;}
  \PY{n}{GD}\PY{p}{.}\PY{n}{cmd\PYZus{}toggle}\PY{p}{(}\PY{l+m+mi}{360}\PY{p}{,} \PY{l+m+mi}{62}\PY{p}{,} \PY{l+m+mi}{80}\PY{p}{,} \PY{l+m+mi}{29}\PY{p}{,} \PY{n}{options}\PY{p}{,} \PY{n}{value}\PY{p}{,}
                \PY{l+s}{\PYZdq{}}\PY{l+s}{that}\PY{l+s}{\PYZdq{}} \PY{l+s}{\PYZdq{}}\PY{l+s+se}{\PYZbs{}xff}\PY{l+s}{\PYZdq{}} \PY{l+s}{\PYZdq{}}\PY{l+s}{this}\PY{l+s}{\PYZdq{}}\PY{p}{)}\PY{p}{;}
  \PY{n}{GD}\PY{p}{.}\PY{n}{cmd\PYZus{}track}\PY{p}{(}\PY{l+m+mi}{360}\PY{p}{,} \PY{l+m+mi}{62}\PY{p}{,} \PY{l+m+mi}{80}\PY{p}{,} \PY{l+m+mi}{20}\PY{p}{,} \PY{n}{TAG\PYZus{}TOGGLE}\PY{p}{)}\PY{p}{;} 
\end{Verbatim}
